# Generated by Django 5.0.1 on 2024-01-17 18:21

import commits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id_commit', models.CharField(default=commits.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(null=True)),
                ('sha', models.CharField(max_length=40, null=True)),
                ('node_id', models.CharField(max_length=100, null=True)),
                ('html_url', models.URLField(null=True)),
                ('comments_url', models.URLField(null=True)),
                ('commit_url', models.URLField(null=True)),
                ('author_name', models.CharField(max_length=100, null=True)),
                ('author_email', models.EmailField(max_length=254, null=True)),
                ('author_date', models.DateTimeField(null=True)),
                ('committer_name', models.CharField(max_length=100, null=True)),
                ('committer_email', models.EmailField(max_length=254, null=True)),
                ('committer_date', models.DateTimeField(null=True)),
                ('message', models.TextField(null=True)),
                ('tree_url', models.URLField(null=True)),
                ('tree_sha', models.CharField(max_length=40, null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('author_login', models.CharField(max_length=100, null=True)),
                ('author_id', models.IntegerField(null=True)),
                ('author_avatar_url', models.URLField(null=True)),
                ('author_html_url', models.URLField(null=True)),
                ('committer_login', models.CharField(max_length=100, null=True)),
                ('committer_id', models.IntegerField(null=True)),
                ('committer_avatar_url', models.URLField(null=True)),
                ('committer_html_url', models.URLField(null=True)),
            ],
        ),
    ]
