# Generated by Django 5.0.1 on 2024-01-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commit',
            table='commit',
        ),
    ]
