# Generated by Django 5.0.1 on 2024-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_alter_commit_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='author_login',
            new_name='repo_name',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_avatar_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_date',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_html_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='comments_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='commit_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_avatar_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_date',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_email',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_html_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_id',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_login',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_name',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='tree_sha',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='tree_url',
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
