# Generated by Django 5.0.1 on 2024-01-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_rename_author_login_commit_repo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='url',
        ),
    ]
