# Generated by Django 5.0.1 on 2024-01-18 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0005_commit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
